import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :leaf, LeafWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
#
# Only the health check is excluded: the probe reaches the pod over plain HTTP with no proxy in
# front of it. A host exclusion would be read off the client's own `Host` header, so anybody
# sending `Host: localhost` would be excluding themselves.
config :leaf, LeafWeb.Endpoint,
  force_ssl: [rewrite_on: [:x_forwarded_proto], exclude: [paths: ["/healthz"]]]

# Everything reaches production over HTTPS, so the session cookie says `Secure`.
config :leaf, secure_cookie: true

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
